import asyncio
import time

import pytest
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.base import AIProvider
from app.ai.router import AIRouter
from app.core.config import settings
from app.core.exceptions import AIProviderTimeoutException, AIProviderUnavailableException
from app.main import app
from app.schemas.ai import AIExplanationRequest, PropertySearchIntent
from app.services.ai_service import AIService


class FailingAIProvider(AIProvider):
    def __init__(self, name: str, exc: Exception):
        self._name = name
        self._exc = exc

    @property
    def provider_name(self) -> str:
        return self._name

    @property
    def model_name(self) -> str:
        return f"{self._name}-mock"

    async def check_health(self):
        return {
            "configured": True,
            "reachable": False,
            "model_available": False,
            "error": str(self._exc),
        }

    async def parse_search_intent(self, user_query: str):
        raise self._exc

    async def explain_property(self, context):
        raise self._exc

    async def explain_comparison(self, context):
        raise self._exc


class DelayedFailingAIProvider(AIProvider):
    def __init__(self, name: str, delay_seconds: float):
        self._name = name
        self._delay_seconds = delay_seconds

    @property
    def provider_name(self) -> str:
        return self._name

    @property
    def model_name(self) -> str:
        return f"{self._name}-delayed"

    async def check_health(self):
        return {"configured": True, "reachable": True, "model_available": True}

    async def parse_search_intent(self, user_query: str):
        await asyncio.sleep(self._delay_seconds)
        raise AIProviderTimeoutException(self._name, self._delay_seconds)

    async def explain_property(self, context):
        await asyncio.sleep(self._delay_seconds)
        raise AIProviderTimeoutException(self._name, self._delay_seconds)

    async def explain_comparison(self, context):
        await asyncio.sleep(self._delay_seconds)
        raise AIProviderTimeoutException(self._name, self._delay_seconds)


class SuccessAIProvider(AIProvider):
    def __init__(self, name: str):
        self._name = name
        self.received_context = None

    @property
    def provider_name(self) -> str:
        return self._name

    @property
    def model_name(self) -> str:
        return f"{self._name}-success"

    async def check_health(self):
        return {
            "configured": True,
            "reachable": True,
            "model_available": True,
            "available_models": [self.model_name],
        }

    async def parse_search_intent(self, user_query: str):
        return (
            PropertySearchIntent(
                raw_query=user_query,
                bedrooms=3,
                max_price=9000000,
                locality="Whitefield",
            ),
            12.5,
        )

    async def explain_property(self, context):
        self.received_context = context
        return (f"Generated by {self._name} successfully.", 15.0)

    async def explain_comparison(self, context):
        self.received_context = context
        return (f"Comparative summary by {self._name}", 15.0)


@pytest.mark.asyncio
async def test_ai_failover_primary_fails_secondary_succeeds(db_session: AsyncSession):
    failing_ollama = FailingAIProvider(
        "ollama", AIProviderUnavailableException("ollama", "Connection refused")
    )
    success_gemini = SuccessAIProvider("gemini")

    AIRouter.register_provider("ollama", failing_ollama)
    AIRouter.register_provider("gemini", success_gemini)

    try:
        service = AIService(db_session)
        # Parse search (profile for standard request -> primary: ollama, fallback: gemini)
        res = await service.parse_search_intent("3 BHK in Whitefield under 90L")

        assert res.provider == "gemini"
        assert res.fallback_used is True
        assert res.intent.bedrooms == 3
        assert res.intent.max_price == 9000000
    finally:
        AIRouter.reset()


@pytest.mark.asyncio
async def test_ai_failover_both_providers_fail_deterministic_fallback(db_session: AsyncSession):
    failing_ollama = FailingAIProvider(
        "ollama", AIProviderUnavailableException("ollama", "Connection refused")
    )
    failing_gemini = FailingAIProvider("gemini", AIProviderTimeoutException("gemini", 20.0))

    AIRouter.register_provider("ollama", failing_ollama)
    AIRouter.register_provider("gemini", failing_gemini)

    try:
        service = AIService(db_session)
        res = await service.parse_search_intent("2 BHK under 50 lakh")

        assert res.provider == "deterministic_fallback"
        assert res.fallback_used is True
        assert res.intent.max_price == 5000000.0
    finally:
        AIRouter.reset()


@pytest.mark.asyncio
async def test_ai_global_time_budget_enforcement(db_session: AsyncSession):
    """
    Test that request execution respects the configured global time deadline.
    Primary consumes budget; fallback receives only remaining budget and halts cleanly.
    """
    orig_budget = settings.AI_TOTAL_TIMEOUT_SECONDS
    settings.AI_TOTAL_TIMEOUT_SECONDS = 0.2  # 200ms tight test budget

    try:
        # Primary takes 0.15s then fails
        slow_ollama = DelayedFailingAIProvider("ollama", 0.15)
        # Fallback takes 0.2s (exceeding remaining budget of 0.05s)
        slow_gemini = DelayedFailingAIProvider("gemini", 0.20)

        AIRouter.register_provider("ollama", slow_ollama)
        AIRouter.register_provider("gemini", slow_gemini)

        service = AIService(db_session)
        start = time.monotonic()
        res = await service.parse_search_intent("2 BHK in Indiranagar")
        elapsed = time.monotonic() - start

        # Must cleanly degrade to deterministic fallback without hanging
        assert res.provider == "deterministic_fallback"
        assert res.fallback_used is True
        # Total time must be bounded around the ~0.2s budget (+- scheduling slack < 1.0s)
        assert elapsed < 1.0
    finally:
        settings.AI_TOTAL_TIMEOUT_SECONDS = orig_budget
        AIRouter.reset()


@pytest.mark.asyncio
async def test_ai_hosted_context_privacy_allowlist(db_session: AsyncSession):
    """
    Test that context passed to hosted AI providers strictly excludes internal DB IDs, owner IDs, and PII.
    """
    gemini_spy = SuccessAIProvider("gemini")
    AIRouter.register_provider("gemini", gemini_spy)

    try:
        import uuid

        from geoalchemy2.shape import from_shape
        from shapely.geometry import Point

        from app.models.property import Property
        from app.models.user import User

        user = User(
            email=f"privacy_{uuid.uuid4().hex[:8]}@estatemap.ai",
            hashed_password="secret_password_hash",
            full_name="Privacy User",
            is_active=True,
        )
        db_session.add(user)
        await db_session.flush()

        prop = Property(
            owner_id=user.id,
            title="Privacy Test Apartment",
            price=6800000.0,
            property_type="apartment",
            bedrooms=2,
            bathrooms=2,
            area_sqft=1100.0,
            address="27th Main",
            city="Bengaluru",
            locality="HSR Layout",
            location=from_shape(Point(77.6446, 12.9121), srid=4326),
            status="active",
        )
        db_session.add(prop)
        await db_session.commit()

        service = AIService(db_session, ai_provider=gemini_spy)
        req = AIExplanationRequest()
        await service.explain_property(property_id=prop.id, request=req)

        # Inspect context captured by the provider spy
        assert gemini_spy.received_context is not None
        prop_ctx = gemini_spy.received_context.get("property", {})

        # Assert ALLOWLIST fields exist
        assert "title" in prop_ctx
        assert "price_inr" in prop_ctx
        assert "bedrooms" in prop_ctx
        assert "locality" in prop_ctx
        assert "city" in prop_ctx

        # Assert FORBIDDEN fields are NOT present in hosted context
        assert "id" not in prop_ctx
        assert "owner_id" not in prop_ctx
        assert "owner" not in prop_ctx
        assert "email" not in prop_ctx
        assert "hashed_password" not in prop_ctx
    finally:
        AIRouter.reset()


@pytest.mark.asyncio
async def test_ai_health_endpoint_multi_provider():
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        res = await client.get("/api/v1/ai/health")
        assert res.status_code == 200
        data = res.json()
        assert data["enabled"] is True
        assert "providers" in data
        assert "ollama" in data["providers"]
        assert "gemini" in data["providers"]
