# -*- coding: utf-8 -*-
# Stories 10 - 13 (Migrations, Soft Delete, Seeding, Connection Pooling)

def get_db2_stories():
    stories = []

    # Story 10
    stories.append({
        'num': 10,
        'title': 'Database Migrations with Alembic',
        'points': 3,
        'why_exists': 'Manual SQL schema updates in production lead to schema drift, unversioned table changes, and zero rollback capabilities during failed deployments.',
        'problem_solved': 'Database schema mismatches between development, staging, and production environments breaking SQL queries and crashing deployments.',
        'prereq_stories': ['Story 07 — PostgreSQL Relational Modeling & Schema Integrity', 'Story 08 — SQLAlchemy 2.0 Declarative Models & Repository Pattern'],
        'prereq_concepts': ['Schema versioning', 'Alembic migration lifecycle (upgrade, downgrade)', 'target_metadata inspection', 'Zero-downtime migrations'],
        'depends_on': [7, 8],
        'unlocks': [11, 12, 81],
        'readiness': [
            'Understand raw SQL DDL (ALTER TABLE, CREATE INDEX)',
            'Familiar with alembic.ini configuration file',
            'Able to explain why database migrations must be forward and backward compatible'
        ],
        'objectives': [
            'Configure alembic/env.py to inspect SQLAlchemy 2.0 Base.metadata asynchronously',
            'Generate auto-detected migration revisions using alembic revision --autogenerate',
            'Apply schema upgrades in Docker container entrypoints using alembic upgrade head'
        ],
        'concepts': [
            'Alembic Version Table: Maintaining alembic_version table in PostgreSQL to track current applied revision hash',
            'Autogenerate Limitations: Recognizing that Alembic autogenerate cannot detect table renames, custom check constraints, or postgis geometry index changes without manual inspection',
            'Async Alembic Runner: Using run_migrations_online() with async engine dispatch via run_sync',
            'Expand and Contract Pattern: Migrating schema in backward-compatible phases to avoid downtime during rolling deployments'
        ],
        'impl': 'backend/alembic/env.py imports Base.metadata from backend/app/models/base.py and executes migrations via do_run_migrations using an async engine wrapper. alembic/versions/ contains versioned migration files defining upgrade() and downgrade().',
        'files': [
            'backend/alembic/env.py',
            'backend/alembic/versions/',
            'backend/alembic.ini',
            'backend/app/db/session.py'
        ],
        'data_flow': 'Developer modifies SQLAlchemy model -> Runs alembic revision --autogenerate -m "add_amenity" -> Alembic compares metadata vs DB -> Generates Python migration script -> Deploy runs alembic upgrade head -> Schema applied atomically in transaction -> alembic_version updated',
        'lab_standalone': '''Build an Alembic migration suite:
1. Initialize alembic init -t async alembic.
2. Configure target_metadata = Base.metadata in alembic/env.py.
3. Add a new column description: Mapped[str] to a model.
4. Run alembic revision --autogenerate -m "add_description".
5. Inspect the generated migration file and run alembic upgrade head.''',
        'lab_mapping': 'Inspect backend/alembic/env.py lines 30-80 and observe how run_async_migrations connects to settings.DATABASE_URL.',
        'acceptance_criteria': [
            'Running alembic upgrade head creates all tables, PostGIS extensions, and indexes.',
            'Alembic version table alembic_version exists in PostgreSQL and matches the latest version script.',
            'Downgrading with alembic downgrade -1 reverts the last applied schema change cleanly.',
            'Auto-generated migrations include foreign keys, not-null constraints, and GiST spatial indexes.'
        ],
        'evidence': [
            'Check current migration version: docker exec estatemap-backend alembic current.',
            'Inspect migration history: docker exec estatemap-backend alembic history.'
        ],
        'outcome_conceptual': 'Complete understanding of relational schema versioning, automated migration generation, and rolling deployment migration patterns.',
        'outcome_impl': 'Ability to configure asynchronous Alembic environments and write safe, reversible database migrations from scratch.',
        'outcome_interview': 'Ability to explain how to manage database schema evolution without downtime in a zero-downtime rolling deployment.',
        'mistakes': [
            'Blindly applying autogenerated migrations without reviewing SQL commands (autogenerate drops tables if names mismatch).',
            'Running non-transactional DDL migrations that leave the database in a broken half-migrated state on failure.',
            'Committing multiple conflicting branch migrations without merging migration heads using alembic merge.'
        ],
        'debug_symptom': 'alembic.util.exc.CommandError: Multiple head revisions are present for given argument \'head\'.',
        'debug_investigate': 'Two feature branches generated migrations concurrently, creating two distinct heads in alembic/versions/.',
        'debug_goal': 'Run alembic merge -m "merge_heads" <head1> <head2> to create a unifying merge revision.',
        'tradeoffs': [
            'Automated Alembic migrations vs Raw SQL scripts (Flyway/Sqitch): Alembic provides deep SQLAlchemy model integration and Python-based data migrations.',
            'Running migrations in container startup vs Standalone CI/CD job: Container startup is convenient for dev/demo; CI/CD job is mandatory for high-availability production clusters.'
        ],
        'prod_current': 'Alembic async environment loading DATABASE_URL from Settings, auto-executed during Docker deployment.',
        'prod_scale': 'Execute migrations via Kubernetes PreSync Hooks before rolling out new application replica pods.',
        'q_basic': 'What is the role of Alembic in a SQLAlchemy-based backend application?',
        'q_impl': 'How does Alembic env.py inspect SQLAlchemy Base.metadata in an asynchronous asyncpg application?',
        'q_tradeoff': 'Why can running alembic upgrade head inside application startup cause race conditions when running multiple server replicas?',
        'q_debug': 'How do you resolve an Alembic migration conflict when two pull requests both create a new migration file?',
        'q_sysdesign': 'How do you perform a zero-downtime column rename in a production PostgreSQL database with 50 million rows?',
        'ans_framework': 'Explain: 1) The Expand and Contract Pattern (Add new col -> Write to both -> Backfill -> Read new -> Drop old), 2) Alembic migration versioning mechanics, 3) Async engine integration in env.py, 4) Why CI/CD deployment jobs must execute migrations before new containers accept traffic.',
        'conn_prev': 'Story 09 established async database access; Story 10 versions the database schema.',
        'conn_next': 'Story 11 implements the Soft Deletion & Audit Fields Pattern on declarative models.',
        'checklist': [
            'Can configure an async Alembic env.py from scratch',
            'Can write explicit upgrade() and downgrade() functions with raw and ORM operations',
            'Can resolve Alembic multiple heads conflicts using alembic merge',
            'Can explain the 3-step Expand and Contract migration pattern'
        ]
    })

    # Story 11
    stories.append({
        'num': 11,
        'title': 'Soft Deletion & Audit Fields Pattern',
        'points': 3,
        'why_exists': 'Hard-deleting records (DELETE FROM properties) permanently erases historical context, breaks referential integrity with past user favorites or interactions, and makes accidental deletion recovery impossible.',
        'problem_solved': 'Accidental property listing deletions permanently destroying analytics history, user favorites, and lead records.',
        'prereq_stories': ['Story 07 — PostgreSQL Relational Modeling & Schema Integrity', 'Story 08 — SQLAlchemy 2.0 Declarative Models & Repository Pattern', 'Story 10 — Database Migrations with Alembic'],
        'prereq_concepts': ['Soft delete (is_deleted / deleted_at)', 'Audit timestamps (created_at, updated_at)', 'SQLAlchemy query filtering', 'Tombstone records'],
        'depends_on': [7, 8, 10],
        'unlocks': [18, 19],
        'readiness': [
            'Understand SQL UPDATE vs DELETE',
            'Familiar with UTC datetime handling in Python',
            'Able to explain why audit trails are required for compliance'
        ],
        'objectives': [
            'Add is_deleted and deleted_at audit columns to base SQLAlchemy models',
            'Implement soft deletion in repositories by updating tombstone flags rather than issuing DELETE SQL',
            'Filter out soft-deleted records automatically in all read and search queries'
        ],
        'concepts': [
            'Soft Deletion: Marking rows with is_deleted = True and deleted_at = utcnow() while retaining raw data for compliance and analytics',
            'Audit Columns: Standardizing id, created_at, updated_at, is_deleted on an abstract base model class',
            'Transparent Repository Filtering: Enforcing where(Property.is_deleted == False) across all repository find and list operations',
            'Hard Delete Pruning: Running background purge jobs to permanently remove tombstone records older than 90 days'
        ],
        'impl': 'backend/app/models/base.py defines abstract class AuditMixin with created_at, updated_at, is_deleted: Mapped[bool] = mapped_column(default=False), and deleted_at: Mapped[Optional[datetime]]. BaseRepository and PropertyRepository enforce where(Model.is_deleted == False) on standard queries.',
        'files': [
            'backend/app/models/base.py (AuditMixin)',
            'backend/app/models/property.py',
            'backend/app/repositories/base_repo.py (delete vs hard_delete)'
        ],
        'data_flow': 'Client sends DELETE /api/v1/properties/123 -> PropertyService calls repo.delete(db, 123) -> Repository executes update(Property).where(Property.id == 123).values(is_deleted=True, deleted_at=utcnow()) -> Row preserved in DB -> Subsequent search queries ignore record',
        'lab_standalone': '''Build a Soft Delete mixin lab:
1. Define class SoftDeleteMixin: is_deleted: Mapped[bool] = False, deleted_at: Mapped[Optional[datetime]] = None.
2. In Repository, implement async def soft_delete(self, id): update values(is_deleted=True).
3. In list query, filter where(is_deleted == False).
4. Verify record still exists in DB table but is excluded from list() results.''',
        'lab_mapping': 'Inspect backend/app/repositories/property_repo.py to see how is_deleted is checked in filter_properties.',
        'acceptance_criteria': [
            'Calling delete endpoint sets is_deleted = True and records UTC timestamp in deleted_at.',
            'Soft-deleted properties never appear in public search, ranking, or viewport map results.',
            'Direct lookup of a soft-deleted property by non-admin returns HTTP 404 Not Found.',
            'Admin users can query soft-deleted records with explicit include_deleted=True flag.'
        ],
        'evidence': [
            'Delete a property: curl -X DELETE http://localhost:8000/api/v1/properties/<id> -H "Authorization: Bearer <token>".',
            'Query DB directly: select id, is_deleted, deleted_at from properties where id = <id>; -> verify is_deleted is true.'
        ],
        'outcome_conceptual': 'Clear understanding of data preservation, auditability, and query-level isolation for deleted entities.',
        'outcome_impl': 'Ability to implement reusable SQLAlchemy audit mixins and soft delete query filters across all repositories.',
        'outcome_interview': 'Ability to articulate the benefits and challenges of soft deletion (e.g. unique constraint collisions and query complexity).',
        'mistakes': [
            'Forgetting the is_deleted == False filter in spatial or aggregate queries, allowing deleted properties to pollute map viewports.',
            'Unique constraint collision: If email or slug has a UNIQUE constraint, soft-deleting user "alice" prevents re-registering "alice" unless using partial unique indexes (WHERE is_deleted = False).',
            'Failing to cascade soft delete to child entities (e.g. property images or favorites).'
        ],
        'debug_symptom': 'Soft-deleted property still appears in map clustering or spatial bounding-box search queries.',
        'debug_investigate': 'Check spatial repository query in backend/app/services/spatial_service.py to ensure Property.is_deleted == False is included in the WHERE clause.',
        'debug_goal': 'Add where(Property.is_deleted.is_(False)) to the spatial query builder.',
        'tradeoffs': [
            'Soft Delete vs Hard Delete: Soft delete protects history and simplifies recovery, but increases table size and requires WHERE filters on every query.',
            'Partial Unique Indexes vs Composite Unique Keys: Partial unique index (CREATE UNIQUE INDEX ON users (email) WHERE is_deleted = FALSE) allows re-use of unique values after soft delete.'
        ],
        'prod_current': 'AuditMixin on all core entities with is_deleted filtering enforced in repositories.',
        'prod_scale': 'Move soft-deleted rows older than 180 days to cold storage (AWS S3 Parquet / BigQuery) via automated archiving tasks.',
        'q_basic': 'What is soft deletion and why is it preferred over hard deletion in enterprise systems?',
        'q_impl': 'How does EstateMap handle unique constraint conflicts when soft-deleting records in PostgreSQL?',
        'q_tradeoff': 'What are the performance costs of soft deletion on index size and query performance over time?',
        'q_debug': 'How do you prevent a soft-deleted property from appearing in cached Redis search responses?',
        'q_sysdesign': 'How would you design a data purging and GDPR "Right to be Forgotten" system in an architecture using soft deletion?',
        'ans_framework': 'Discuss: 1) Rationale (audit compliance, relational integrity with past interactions), 2) Implementation (AuditMixin + is_deleted filter in repositories), 3) Solving unique constraint collisions with PostgreSQL partial indexes (WHERE is_deleted = FALSE), 4) GDPR compliance via hard anonymization.',
        'conn_prev': 'Story 10 established database migrations; Story 11 adds soft deletion columns and audit mixins.',
        'conn_next': 'Story 12 creates deterministic database seeders and test fixtures.',
        'checklist': [
            'Can create a reusable SQLAlchemy AuditMixin with timestamp and soft-delete columns',
            'Can write PostgreSQL partial unique indexes to support soft delete uniqueness',
            'Can implement transparent soft-delete filtering in repository queries',
            'Can explain how to handle GDPR hard-delete mandates in a soft-deleted database'
        ]
    })

    # Story 12
    stories.append({
        'num': 12,
        'title': 'Database Seeding & Deterministic Test Fixtures',
        'points': 3,
        'why_exists': 'Empty databases prevent frontend developers, testers, and automated CI pipelines from verifying map visualization, search ranking, and comparison workflows. Realistic seed data is required for deterministic validation.',
        'problem_solved': 'Inconsistent demo data across environments causing intermittent test failures and preventing accurate spatial clustering testing.',
        'prereq_stories': ['Story 07 — PostgreSQL Relational Modeling & Schema Integrity', 'Story 08 — SQLAlchemy 2.0 Declarative Models & Repository Pattern', 'Story 10 — Database Migrations with Alembic'],
        'prereq_concepts': ['Idempotent data seeding', 'Deterministic geospatial coordinates', 'Pytest fixtures', 'Test data factories'],
        'depends_on': [7, 8, 10],
        'unlocks': [18, 86],
        'readiness': [
            'Understand SQL INSERT with ON CONFLICT DO NOTHING',
            'Familiar with GeoJSON coordinate format ([longitude, latitude])',
            'Able to explain why test fixtures must be repeatable and deterministic'
        ],
        'objectives': [
            'Implement an idempotent database seeder generating 100+ realistic properties across Chennai and Bengaluru',
            'Seed diverse Points of Interest (Metro stations, Tech parks, Schools, Hospitals, Supermarkets)',
            'Integrate seeding into FastAPI lifespan startup and Pytest test fixtures'
        ],
        'concepts': [
            'Idempotent Seeding: Designing seed scripts that can run repeatedly without duplicating existing database rows',
            'Realistic Spatial Distribution: Placing properties and POIs at real-world coordinates to test distance and commute calculations',
            'Deterministic Test States: Ensuring every test run starts with an identical, predictable database state',
            'Multi-City Multi-Tier Diversity: Seeding budget, mid-tier, and luxury listings across multiple cities (Chennai, Bengaluru)'
        ],
        'impl': 'backend/app/db/seed.py and backend/app/db/seed_chennai.py define seed_properties(db) and seed_pois(db). They populate 104 properties (100 Chennai + 4 Bengaluru) and 29 POIs with exact WGS84 coordinates, prices, and amenities, guarded by if not await repo.count().',
        'files': [
            'backend/app/db/seed.py',
            'backend/app/db/seed_chennai.py',
            'backend/app/main.py (lifespan auto-seed)',
            'backend/tests/conftest.py'
        ],
        'data_flow': 'Lifespan boot / Test setup -> Check if properties table count == 0 -> If empty, iterate seed data catalog -> Insert properties with ST_SetSRID(ST_MakePoint(lng, lat), 4326) -> Insert POIs -> Commit transaction -> 104 properties ready for search',
        'lab_standalone': '''Build an idempotent seeder lab:
1. Define a list of 5 property dictionaries with realistic coordinates.
2. Write async def seed(db): for item in data: check if exists by title; if not, insert.
3. Run seeder twice in succession; verify database has exactly 5 rows, not 10.''',
        'lab_mapping': 'Inspect backend/app/db/seed_chennai.py to observe the 100 Chennai property listings spanning Anna Nagar, OMR, Velachery, T. Nagar, and Adyar.',
        'acceptance_criteria': [
            'Running the seeder populates exactly 104 properties and 29 POIs.',
            'Re-running the seeder is idempotent (does not duplicate existing records).',
            'All seeded properties have valid WGS84 coordinates inside Chennai or Bengaluru bounding boxes.',
            'Seed data includes diverse property types (Apartments, Villas, Penthouses) across wide price spectrums.'
        ],
        'evidence': [
            'Count properties in database: docker exec estatemap-postgres psql -U postgres -d estatemap -c "SELECT city, count(*) FROM properties GROUP BY city;".',
            'Verify 100 Chennai and 4 Bengaluru listings returned.'
        ],
        'outcome_conceptual': 'Mastery of test data management, idempotent database seeding, and realistic spatial dataset construction.',
        'outcome_impl': 'Ability to create production-grade database seeders and Pytest fixture hierarchies from scratch.',
        'outcome_interview': 'Ability to explain how idempotent seeding and deterministic test fixtures prevent flaky integration tests.',
        'mistakes': [
            'Hardcoding seeder with blind INSERT statements without checking for existence, causing duplicate key crashes on re-runs.',
            'Using inverted coordinates (lat, lng instead of lng, lat) when generating PostGIS POINT geometries.',
            'Seeding unrealistically clustered data that fails to trigger spatial bounding-box partitioning logic.'
        ],
        'debug_symptom': 'Database property count doubles every time the application server restarts in development.',
        'debug_investigate': 'Check backend/app/main.py lifespan function to see if seed_properties checks existing count before executing inserts.',
        'debug_goal': 'Wrap seed logic in if await repo.get_total_count(db) == 0: check.',
        'tradeoffs': [
            'Code-based Python seeders vs SQL dump restoration: Python seeders allow dynamic password hashing and dynamic coordinate calculations; SQL dumps are faster for gigabyte-scale datasets.',
            'Auto-seeding in Lifespan vs Manual CLI command: Lifespan auto-seeding provides instant out-of-the-box local developer ergonomics.'
        ],
        'prod_current': 'Idempotent Python seeder executed during lifespan boot if database is empty.',
        'prod_scale': 'Use PostgreSQL pg_restore from anonymized production snapshots for staging environment initialization.',
        'q_basic': 'Why is idempotency essential when writing database seeding scripts?',
        'q_impl': 'How does EstateMap seed spatial geometry columns with valid PostGIS POINT representations?',
        'q_tradeoff': 'What are the pros and cons of running database seeds inside application startup versus a standalone migration script?',
        'q_debug': 'How do you diagnose why spatial bounding-box search returns zero listings for Chennai after running the seed script?',
        'q_sysdesign': 'How do you generate 10 million synthetic real estate listings with realistic spatial density distributions for stress testing?',
        'ans_framework': 'Explain: 1) The role of seed data in developer onboarding and end-to-end testing, 2) Idempotency guarantee (count check / ON CONFLICT), 3) PostGIS POINT(lng, lat) coordinate geometry insertion, 4) EstateMap 104-property seed architecture.',
        'conn_prev': 'Story 11 established soft delete models; Story 12 populates those models with realistic seed data.',
        'conn_next': 'Story 13 optimizes database connection pooling to prevent pool exhaustion under load.',
        'checklist': [
            'Can write an idempotent database seeder using SQLAlchemy async',
            'Can insert spatial POINT geometries with correct WGS84 SRID 4326',
            'Can configure Pytest fixtures to seed and roll back transactions cleanly',
            'Can explain why GeoJSON [lng, lat] order differs from common latitude-longitude speech'
        ]
    })

    # Story 13
    stories.append({
        'num': 13,
        'title': 'Connection Pooling & Pool Exhaustion Prevention',
        'points': 5,
        'why_exists': 'Establishing a new TCP and TLS connection to PostgreSQL costs 30-100ms and consumes 2-10MB of memory on the database server. Connection pooling maintains pre-warmed database sockets, but misconfigured pool sizes cause connection starvation and 500 errors under load.',
        'problem_solved': 'Sudden traffic spikes exhausting PostgreSQL max_connections, causing server crashes, connection timeouts, and cascading failure across the application.',
        'prereq_stories': ['Story 02 — FastAPI Lifespan & Application Lifecycle', 'Story 06 — Structured Logging & Distributed Request IDs', 'Story 09 — Non-Blocking Async Database Access with Asyncpg'],
        'prereq_concepts': ['SQLAlchemy QueuePool', 'Connection Pool Sizing formula', 'pool_pre_ping & connection staleness', 'Connection leaks & timeout handling'],
        'depends_on': [2, 6, 9],
        'unlocks': [86, 92],
        'readiness': [
            'Understand PostgreSQL max_connections setting',
            'Familiar with SQLAlchemy pool_size, max_overflow, pool_timeout, and pool_recycle',
            'Able to explain why unclosed sessions leak database connections'
        ],
        'objectives': [
            'Configure SQLAlchemy QueuePool with optimal pool_size (20), max_overflow (10), and pool_timeout (30s)',
            'Enable pool_pre_ping=True to transparently detect and discard stale or dropped PostgreSQL connections',
            'Implement strict request session cleanup in FastAPI get_db dependency to prevent socket descriptor leaks'
        ],
        'concepts': [
            'Connection Pooling: Reusing a fixed pool of persistent database connections across thousands of concurrent HTTP requests',
            'Pool Sizing Math: Calculating optimal pool size: Pool Size = (Concurrent CPU Cores * 2) + Effective Spindle Count',
            'Pool Pre-Ping: Emitting lightweight "SELECT 1" heartbeat check before handing connection to application to prevent stale connection errors',
            'Connection Leak Mitigation: Ensuring AsyncSession is wrapped in try/finally or async with to guarantee return to pool even on uncaught exceptions'
        ],
        'impl': 'backend/app/db/session.py configures create_async_engine(settings.DATABASE_URL, pool_size=20, max_overflow=10, pool_timeout=30.0, pool_recycle=1800, pool_pre_ping=True). FastAPI dependency get_db yields session in try block and closes in finally block.',
        'files': [
            'backend/app/db/session.py',
            'backend/app/api/deps.py (get_db)',
            'backend/app/core/config.py'
        ],
        'data_flow': 'FastAPI Request -> get_db() checks QueuePool -> Checks out pre-warmed connection (runs pre-ping if idle) -> Executes query -> get_db finally block executes session.close() -> Connection returned to QueuePool for reuse -> Zero TCP teardown overhead',
        'lab_standalone': '''Build a connection pool stress test:
1. Create SQLAlchemy engine with pool_size=5, max_overflow=0, pool_timeout=2.0.
2. Launch 10 concurrent async tasks that hold the session with await asyncio.sleep(5).
3. Observe tasks 1-5 acquire connections while tasks 6-10 wait.
4. Verify task 6 raises sqlalchemy.exc.TimeoutError after 2.0 seconds timeout.''',
        'lab_mapping': 'Inspect backend/app/db/session.py lines 15-35 to examine pool configuration and pool_pre_ping settings.',
        'acceptance_criteria': [
            'Engine maintains a steady pool of pre-warmed connections without opening new TCP connections per request.',
            'Dropped or restarted PostgreSQL connections are automatically discarded by pool_pre_ping without throwing 500 errors.',
            'Under high concurrency exceeding pool_size, requests wait up to pool_timeout seconds before timing out cleanly.',
            'All checked-out connections are guaranteed to be returned to the pool after request completion.'
        ],
        'evidence': [
            'Inspect active PostgreSQL connections: docker exec estatemap-postgres psql -U postgres -d estatemap -c "SELECT count(*) FROM pg_stat_activity WHERE datname=\'estatemap\';".',
            'Run concurrent load test: verify connection count stays within pool_size + max_overflow bound.'
        ],
        'outcome_conceptual': 'Mastery of database connection pooling dynamics, socket reuse, and concurrency bottleneck mitigation.',
        'outcome_impl': 'Ability to configure and tune enterprise-grade connection pools in SQLAlchemy and asyncpg for high-throughput backends.',
        'outcome_interview': 'Ability to explain the exact math behind database connection pool sizing and explain how PgBouncer scales PostgreSQL to 10,000+ connections.',
        'mistakes': [
            'Setting pool_size=100 on every FastAPI container, exhausting PostgreSQL max_connections when running 5 container replicas (5 * 100 = 500 connections).',
            'Omitting pool_pre_ping=True, causing intermittent "server closed the connection unexpectedly" errors after database idle periods.',
            'Failing to close AsyncSession in exception handlers, causing connection pool exhaustion in production.'
        ],
        'debug_symptom': 'sqlalchemy.exc.TimeoutError: QueuePool limit of size 20 overflow 10 reached, connection timed out, timeout 30.00.',
        'debug_investigate': 'Check for long-running slow queries holding connections or endpoints that instantiate sessions without closing them in a finally block.',
        'debug_goal': 'Profile slow queries with pg_stat_activity and ensure get_db dependency uses proper try/finally context management.',
        'tradeoffs': [
            'Application-level pooling (SQLAlchemy QueuePool) vs Dedicated Proxy Pooling (PgBouncer): Application pooling works seamlessly for single containers; PgBouncer is required when horizontally scaling across multiple Kubernetes nodes.',
            'Small pool vs Large pool: Smaller pools (20-30) maximize CPU cache locality and reduce DB memory thrashing; overly large pools degrade PostgreSQL throughput.'
        ],
        'prod_current': 'SQLAlchemy QueuePool with pool_size=20, max_overflow=10, pool_pre_ping=True.',
        'prod_scale': 'Deploy PgBouncer in Transaction Pooling mode in front of PostgreSQL, allowing thousands of application pods to share 100 database connections.',
        'q_basic': 'What is a database connection pool and why is it used instead of opening a new connection per request?',
        'q_impl': 'What does pool_pre_ping=True do in SQLAlchemy and why is it essential in cloud environments with network firewalls?',
        'q_tradeoff': 'How do you calculate the optimal connection pool size for a PostgreSQL database server?',
        'q_debug': 'How do you diagnose and fix connection pool exhaustion (QueuePool TimeoutError) in a FastAPI backend?',
        'q_sysdesign': 'How does PgBouncer transaction pooling differ from session pooling, and what limitations does transaction pooling impose on application SQL?',
        'ans_framework': 'Explain: 1) The cost of connection establishment (TCP handshake + TLS + Postgres backend fork), 2) Pool sizing math: (2 * Cores) + Disk spindles, 3) Pool starvation root causes (slow queries & unclosed sessions), 4) EstateMap session.py configuration + PgBouncer scaling roadmap.',
        'conn_prev': 'Story 12 established database seeding; Story 13 protects the database connection pool under heavy query traffic.',
        'conn_next': 'Story 18 implements core Property CRUD domain services on top of this pooled async database infrastructure.',
        'checklist': [
            'Can configure pool_size, max_overflow, pool_timeout, and pool_pre_ping in SQLAlchemy',
            'Can calculate database pool size limits across multiple application container instances',
            'Can detect connection leaks using PostgreSQL pg_stat_activity',
            'Can explain the architectural difference between QueuePool and PgBouncer'
        ]
    })

    return stories
